# Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Terminal e compatibilidade com Neovim
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm*:Tc"

# Habilita eventos de foco (necessário para vim-tmux-navigator)
set -g focus-events on

# Estilo e usabilidade
set -g mode-keys vi
set -g mouse on
set -g base-index 1
set -g status-bg black
set -g status-fg white

# Layouts e navegação entre janelas/panes
bind-key -r Space next-layout
bind q kill-pane -a -t 0 
bind v split-window -v -l 30% -c "#{pane_current_path}" 
bind | split-window -h -l 30% -c "#{pane_current_path}"
bind _ split-window -v -l 30% -c "#{pane_current_path}"
bind i split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind-key r source-file ~/.tmux.conf

# Mover janelas
bind -r C-S-Left swap-window -t -1
bind -r C-S-Right swap-window -t +1

# Redimensionar panes
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @tmux_power_theme 'sky'
set -g @tmux_power_date_icon ''
set -g @tmux_power_time_icon ''
set -g @tmux_power_user_icon ''
set -g @tmux_power_session_icon ''
set -g @tmux_power_left_arrow_icon ''
set -g @tmux_power_right_arrow_icon ''

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
